name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
#    - name: Install Docker
#      run: |
#        apt-get remove docker docker-engine docker.io containerd runc
#        apt-get update
#        apt-get install \
#          ca-certificates \
#           curl \
#           gnupg \
#           lsb-release
#        mkdir -p /etc/apt/keyrings
#        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#        echo \
#          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
#          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#        apt-get update
#        apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
#        apt-get remove nginx* && sudo apt-get install nginx-full
#        docker compose version
    - name: Build the base Docker image
      run: |
        cd aio-base
        docker build -t axelor/aio-base .
    - name: Build the builder Docker image
      run: |
        cd aio-builder
        docker build -t axelor/aio-builder .
    - name: Build the app Docker image
      run: |
        cd aio-erp
        docker build -t axelor/aio-erp .
    
#     - name: Run app container
#       run: docker run -p 8080:80 axelor/aio-erp &
        
